config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :invoices do
    get :collection
    collection do
      get :pending
    end
  end
  resources :collections
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :invoice
  validates_presence_of :invoice_id
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :collections
  validates :customer_name, presence: true
  validates :brand_manager, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
    # def new
    #     @invoice = Invoice.find(params[:id])
    #     @collections = @invoice.collections
    #     @amounts = []
    #     @collections.each do |collection|
    #         @amounts << collection.amount
    #     end
    # end
    # def create
    #     @collection = Collection.new(collection_params)
    #     if @collection.save
    #         flash[:notice] = "Collection Created"
    #         redirect_to invoices_path
    #     else
    #         flash[:error] = @collection.errors.full_messages.join(', ').html_safe
    #         render :new
    #     end
    # end
    # def collection_params
    #     params.require(:collection).permit(:amount, :reference, :collection_date)
    # end
    
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    def new
        @invoice = Invoice.new
    end

    def create
        @invoice = Invoice.new(invoice_params)
        if @invoice.save
            flash[:notice] = "Invoice Created"
            redirect_to invoices_path
        else
            flash[:error] = @invoice.errors.full_messages.join(', ').html_safe
            render :new
        end
    end

# Collection
    def create_collection
        @collection = Collection.new(collection_params)
        if @collection.save
            flash[:notice] = "Collection Created"
            redirect_to invoices_path
        else
            flash[:error] = @collection.errors.full_messages.join(', ').html_safe
            render :new
        end
    end
    def collection_params
        params.require(:collection).permit(:amount, :reference, :collection_date)
    end

    def index
        @invoices = Invoice.all
        # @invoice = Invoice.find(params[:id])
        # @collections = @invoice.collections
        # @amounts = []
        # @collections.each do |collection|
        #     @amounts << collection.amount
        # end
    end
    def collection
        # @invoice = Invoice.find(params[:id])
        # @collections = @invoice.collections
        # @amounts = []
        # @collections.each do |collection|
        #     @amounts << collection.amount
        # end
        @collection = Collection.new
    end

    def show
        @invoice = Invoice.find(params[:id])
    end
    def pending
        @invoices = Invoice.includes(:collections).where("amount < ?", 0)
        render :index
    end
    def invoice_params
        params.require(:invoice).permit(:brand_manager, :narration, :amount, :customer_name, :reference, :invoice_date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_controller_helper.rb
module BillsControllerHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/invoices_controller_helper.rb
module InvoicesControllerHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/collection.html.erb
<div class="row">
    <div class="col-md-8">
        <%= form_for @collection, url: {action: "create_collection" } do |c| %>
            <div class="form-group">
                <%= c.label :amount %>
                <%= c.number_field :amount %>
            </div>
            <div class="form-group">
                <%= c.label :reference %>
                <%= c.text_field :reference %>
            </div>
            <div class="form-group">
                <%= c.label :Collection_Date %>
                <%= c.date_field :collection_date %>
            </div>
            <%= c.submit %>
        <% end %>
    </div>
</div>

app/views/invoices/index.html.erb
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-4"><%= link_to "Add a New Bill", new_invoice_path, class: "btn btn-primary" %></div>
            <div class="col-md-4"><%= link_to "Show Pending Bills", pending_invoices_path, class: "btn btn-primary" %></div>
            <div class="col-md-4"><%= link_to "Show Collected Bills", invoices_path, class: "btn btn-primary" %></div>
        </div>
        <div class="card">
            <h2 class="card-header text-center">
                <div class="float-left"> List Of Invoices </div>
            </h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Reference</th>
                        <th>Invoice Date</th>
                        <th>Customer</th>
                        <th>Brand Manager</th>
                        <th>Narration</th>
                        <th>Amount</th>
                        <th>Total Collection</th>
                        <th>Balance Due</th>
                        <th>Add Collection</th>
                    </tr>
                </thead>
                <tbody>
                    <% @invoices.each do |invoice| %>
                    <% total = invoice.collections %>
                    <tr>
                        <td><%= link_to invoice.reference, invoice_path(invoice) %></td>
                        <td><%= invoice.invoice_date.strftime("%F") %></td>
                        <td><%= invoice.customer_name %></td>
                        <td><%= invoice.brand_manager %></td>
                        <td><%= invoice.narration %></td>
                        <td><%= invoice.amount %></td>
                        <td><%= total.sum(:amount) %></td>
                        <td><%= invoice.amount - total.sum(:amount) %></td>
                        <td><%= link_to "Add", invoice_collection_path(invoice) %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/invoices/new.html.erb
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-8 pt-2">
        <%= form_for(@invoice) do |i| %>
            <div class="form-group">
                <%= i.label :Brand_Manager %><br>
                <%= i.text_field :brand_manager %>
            </div>
            <div class="form-group">
                <%= i.label :Narration %><br>
                <%= i.text_field :narration %>
            </div>
            <div class="form-group">
                <%= i.label :Amount %><br>
                <%= i.number_field :amount %>
            </div>
            <div class="form-group">
                <%= i.label :Customer_Name %><br>
                <%= i.text_field :customer_name %>
            </div>
            <div class="form-group">
                <%= i.label :reference %><br>
                <%= i.text_field :reference %>
            </div>
            <div class="form-group">
                <%= i.label :Invoice_Date %><br>
                <%= i.date_field :invoice_date %>
            </div>
            <%= i.submit %>
        <% end %>
    </div>
</div>

app/views/invoices/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr><div style="color:#85C5D1"><%= @invoice.reference %></div></tr>
                    <tr><div> <%= @invoice.customer_name %> </div></tr>
                    <tr><div><%= @invoice.brand_manager %></div></tr>
                    <tr><div><%= @invoice.narration %></div></tr>
                </thead>
            </table>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Event</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <% @total = @invoice.collections %>
                    <tr>
                        <td style="padding: 0.2em"><%= @invoice.invoice_date&.strftime("%F") %></td>
                        <td>New Invoice</td>
                        <td><%= @invoice&.amount %></td>
                    </tr>
                    <tr>
                        <td style="padding: 0.2em"><%= @invoice&.collections.last&.collection_date&.strftime("%F") %></td>
                        <td>Collection</td>
                        <td><%= @total&.sum(:amount) %></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Balance</td>
                        <td style="padding: 0.2em"><%= @invoice.amount - @total&.sum(:amount) %></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>